# Generated by Django 3.2.8 on 2021-11-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], max_length=10),
        ),
    ]
