# Generated by Django 3.2.8 on 2021-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('processing', 'Processing'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='unpaid', max_length=10, verbose_name='Delivery status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.BigIntegerField(verbose_name='Postal Code'),
        ),
    ]
