# Generated by Django 3.2.8 on 2021-10-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='small_descpription',
            new_name='small_description',
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Alternative text'),
        ),
    ]
